name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
    # Paths can be used only to trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - '*.md'
     # - 'images/**'
 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  makepdfs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: mkrakowitzer/actions-makepdfs@master
      if: github.ref == 'refs/heads/master'
      with:
        markdown_dir: ./
        output_dir: pdfs
    - uses: actions/upload-artifact@v1
      with:
        name: platform-architecture-docs
        path: pdfs
